name: CI

on:
    push:

jobs:
    coverage:
        name: "Coverage"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: ls /usr/local/lib/python3.10/dist-packages
            - run: python -m pip freeze
            - run: python -m pip install --upgrade pip
            - run: python -m pip install numpy pin pin-pink
            - run: python -m pip freeze
            - run: python -c "import sys; print(sys.path)"
            - run: python -c "import tomli; print(tomli.__file__)"
            - run: python -m pip install --force-reinstall tomli
            - run: tools/bazelisk coverage --combined_report=lcov --compilation_mode=fastbuild --instrument_test_targets //...
